
stages:

  # 项目启动
  - project_start


variables:
  XINQIU_PROJECT: web-api


# 拉取代码
project_start:
  stage: project_start
  only:
    - test
  tags:
    - jdk1.8_144
  script:
    - cd /usr/local/git/
    - ./build.sh

